var items = ['Milkshake','Sandwich','Chai','Milkshake','Sandwich','Chai','Milkshake','Sandwich','Chai','Milkshake','Sandwich','Chai','Milkshake','Sandwich','Chai']
var total = ['Subtotal','Packaging','Taxes @ 5%','Total']

var menu = {
    items:[{category:'milkshake',
     name:'Apple Milskshake',
     price:'120'},
     {category:'milkshake',
     name:'Chikuu Milskshake',
     price:'120'},
     {category:'milkshake',
     name:'Avacado Milskshake',
     price:'140'},
     {category:'milkshake',
     name:'Strawberry Milskshake',
     price:'100'},
     {category:'milkshake',
     name:'Mango Milskshake',
     price:'150'},
     {category:'milkshake',
     name:'Lychee Milskshake',
     price:'180'},
     
     {category:'sandwich',
     name:'Veg Grill',
     price:'90'},
     {category:'sandwich',
     name:'Club Cheese Sandwich',
     price:'100'},
     {category:'sandwich',
     name:'Glazed Banana Honey Toast',
     price:'80'},
     {category:'sandwich',
     name:'Aloo Tikki Sub',
     price:'80'},
     {category:'sandwich',
     name:'Chilli Corn Sandwich',
     price:'100'},
     {category:'sandwich',
     name:'Speacial Sandwich',
     price:'120'},

     {category:'juice',
     name:'Anar juice',
     price:'180'},
     {category:'juice',
     name:'Lemon Juice',
     price:'50'},
     {category:'juice',
     name:'Honey Lemon juice',
     price:'60'},
     {category:'juice',
     name:'Blazing Gun Mocktail',
     price:'100'},
     {category:'juice',
     name:'Virgin Mohito',
     price:'90'},
     {category:'juice',
     name:'Classic Iced Tea',
     price:'100'},

     {category:'desserts',
     name:'Chocolate Lava Cake',
     price:'100'},
     {category:'desserts',
     name:'Ice cream Bowl',
     price:'80'},
     {category:'desserts',
     name:'Mango Cream',
     price:'180'},
     {category:'desserts',
     name:'Sizzling Brownie',
     price:'180'},
     {category:'desserts',
     name:'Fruit Salad',
     price:'140'},
     {category:'desserts',
     name:'Art of Delight',
     price:'200'},
    ]
}

// console.log(menu)